macro(SetupTBB)
    option(FREECAD_USE_TBB "Enable Intel oneTBB parallel algorithms when the library is present" ON)
    if(FREECAD_USE_TBB)
        find_package(TBB QUIET)
        if(TBB_FOUND)
            set(HAVE_TBB ON)
            message(STATUS "Found TBB ${TBB_VERSION}")
        else()
            message(STATUS "TBB not found; ImportOCAF parallel paths remain disabled")
        endif()
    endif()
endmacro(SetupTBB)
